project:
  type: book

book:
  title: "ML1 Portoflio"
  author: "Ziqian Zhang"
  date: "9/16/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - 01-performance-measures.qmd
    - 02-partial-effect-plots.qmd
    - 03-4-models.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  # pdf:
  #   documentclass: scrreprt



